/**
 * Tests for summary.ts — meeting summary generation and distribution.
 * Issue #6 — NostraAIAgent.
 */

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import type { Intent, CreatedIssue } from '../models.js';
import type { OpenClawConfig } from '../config.js';

// Hoist mock functions
const { mockAxiosPost, mockWriteFile, mockMkdir } = vi.hoisted(() => ({
  mockAxiosPost: vi.fn(),
  mockWriteFile: vi.fn(),
  mockMkdir: vi.fn(),
}));

// Mock axios
vi.mock('axios', () => ({
  default: {
    post: mockAxiosPost,
  },
}));

// Mock fs/promises
vi.mock('node:fs/promises', () => ({
  writeFile: mockWriteFile,
  mkdir: mockMkdir,
}));

// Import after mocks
import { generateAndSendSummary } from '../summary.js';
import { MeetingSession } from '../session.js';

const mockConfig: OpenClawConfig = {
  instanceName: 'test-bot',
  recallApiKey: 'test-recall',
  elevenLabsApiKey: 'test-eleven',

  githubToken: null,
  githubRepo: null,
  telegramBotToken: 'bot123456:ABC-DEF',
  telegramChatId: '-1001234567890',
  confidenceThreshold: 0.85,
};

const createIntent = (overrides: Partial<Intent> = {}): Intent => ({
  id: 'intent-1',
  type: 'BUG',
  text: 'Fix login issue',
  owner: 'Alice',
  deadline: null,
  priority: 'high',
  confidence: 0.92,
  sourceQuote: 'We need to fix the login issue',
  ...overrides,
});

const createIssue = (overrides: Partial<CreatedIssue> = {}): CreatedIssue => ({
  intentText: 'Fix login issue',
  issueUrl: 'https://github.com/owner/repo/issues/42',
  issueNumber: 42,
  title: 'Bug: Fix login issue',
  ...overrides,
});

describe('generateAndSendSummary', () => {
  let session: MeetingSession;
  let consoleSpy: ReturnType<typeof vi.spyOn>;

  beforeEach(() => {
    vi.clearAllMocks();
    vi.useFakeTimers();
    vi.setSystemTime(new Date('2026-03-27T14:30:00Z'));
    session = new MeetingSession('https://meet.google.com/abc-def-ghi', mockConfig);
    mockWriteFile.mockResolvedValue(undefined);
    mockMkdir.mockResolvedValue(undefined);
    mockAxiosPost.mockResolvedValue({ data: { ok: true } });
    consoleSpy = vi.spyOn(console, 'error').mockImplementation(() => {});
  });

  afterEach(() => {
    vi.restoreAllMocks();
    vi.useRealTimers();
  });

  describe('markdown generation', () => {
    it('should generate correct markdown with intents, issues, and decisions', async () => {
      const intent = createIntent();
      const issue = createIssue();
      session.addIntent(intent);
      session.addCreatedIssue(issue);
      session.decisions.push('Use TypeScript for the new service');

      await generateAndSendSummary(session, mockConfig);

      const writtenContent = mockWriteFile.mock.calls[0][1] as string;
      expect(writtenContent).toContain('# Meeting Summary');
      expect(writtenContent).toContain('**Date:** 2026-03-27 14:30');
      expect(writtenContent).toContain('**Meeting:** https://meet.google.com/abc-def-ghi');
      expect(writtenContent).toContain('## GitHub Issues Created');
      expect(writtenContent).toContain('[Bug: Fix login issue](https://github.com/owner/repo/issues/42)');
      expect(writtenContent).toContain('## Decisions');
      expect(writtenContent).toContain('- Use TypeScript for the new service');
      expect(writtenContent).toContain('## All Detected Items');
      expect(writtenContent).toContain('**BUG** [high]: Fix login issue -> Alice');
      expect(writtenContent).toContain('*Generated by MeetingClaw*');
    });

    it('should show "None" when no issues created', async () => {
      const intent = createIntent({ type: 'TODO' });
      session.addIntent(intent);

      await generateAndSendSummary(session, mockConfig);

      const writtenContent = mockWriteFile.mock.calls[0][1] as string;
      expect(writtenContent).toContain('## GitHub Issues Created\nNone');
    });

    it('should show "None" when no decisions', async () => {
      const intent = createIntent({ type: 'BUG' });
      session.addIntent(intent);

      await generateAndSendSummary(session, mockConfig);

      const writtenContent = mockWriteFile.mock.calls[0][1] as string;
      expect(writtenContent).toContain('## Decisions\nNone');
    });

    it('should handle intent without owner', async () => {
      const intent = createIntent({ owner: null });
      session.addIntent(intent);

      await generateAndSendSummary(session, mockConfig);

      const writtenContent = mockWriteFile.mock.calls[0][1] as string;
      expect(writtenContent).toContain('**BUG** [high]: Fix login issue');
      expect(writtenContent).not.toContain('-> null');
    });
  });

  describe('zero intents handling', () => {
    it('should use "No action items detected" message when session has zero intents', async () => {
      await generateAndSendSummary(session, mockConfig);

      const writtenContent = mockWriteFile.mock.calls[0][1] as string;
      expect(writtenContent).toContain('No action items detected in this meeting.');
    });
  });

  describe('Telegram integration', () => {
    it('should call axios.post with correct URL and body when Telegram is configured', async () => {
      const intent = createIntent();
      session.addIntent(intent);

      await generateAndSendSummary(session, mockConfig);

      expect(mockAxiosPost).toHaveBeenCalledWith(
        'https://api.telegram.org/botbot123456:ABC-DEF/sendMessage',
        {
          chat_id: '-1001234567890',
          text: expect.stringContaining('# Meeting Summary'),
          parse_mode: 'Markdown',
        },
      );
    });

    it('should not call axios when Telegram bot token is missing', async () => {
      const configNoToken = { ...mockConfig, telegramBotToken: null };
      const intent = createIntent();
      session.addIntent(intent);

      await generateAndSendSummary(session, configNoToken);

      expect(mockAxiosPost).not.toHaveBeenCalled();
    });

    it('should not call axios when Telegram chat ID is missing', async () => {
      const configNoChatId = { ...mockConfig, telegramChatId: null };
      const intent = createIntent();
      session.addIntent(intent);

      await generateAndSendSummary(session, configNoChatId);

      expect(mockAxiosPost).not.toHaveBeenCalled();
    });

    it('should truncate Telegram message to 4096 chars if summary is long', async () => {
      // Create a session with many intents to generate a long summary
      for (let i = 0; i < 200; i++) {
        session.addIntent(createIntent({
          id: `intent-${i}`,
          text: `This is a very long intent description number ${i} that will make the summary exceed the Telegram limit`,
        }));
      }

      await generateAndSendSummary(session, mockConfig);

      const telegramText = mockAxiosPost.mock.calls[0][1].text as string;
      expect(telegramText.length).toBeLessThanOrEqual(4096);
    });
  });

  describe('error handling', () => {
    it('should log error but not throw when Telegram call fails', async () => {
      mockAxiosPost.mockRejectedValue(new Error('Telegram API Error'));
      const intent = createIntent();
      session.addIntent(intent);

      await expect(generateAndSendSummary(session, mockConfig)).resolves.not.toThrow();
      expect(consoleSpy).toHaveBeenCalledWith(
        expect.stringContaining('Telegram'),
        expect.any(Error),
      );
    });

    it('should log error but not throw when file write fails', async () => {
      mockWriteFile.mockRejectedValue(new Error('File write error'));
      const intent = createIntent();
      session.addIntent(intent);

      await expect(generateAndSendSummary(session, mockConfig)).resolves.not.toThrow();
      expect(consoleSpy).toHaveBeenCalledWith(
        expect.stringContaining('file'),
        expect.any(Error),
      );
    });

    it('should still attempt Telegram send even if file write fails', async () => {
      mockWriteFile.mockRejectedValue(new Error('File write error'));
      const intent = createIntent();
      session.addIntent(intent);

      await generateAndSendSummary(session, mockConfig);

      expect(mockAxiosPost).toHaveBeenCalled();
    });
  });

  describe('file saving', () => {
    it('should save file to correct path with meetingId', async () => {
      const intent = createIntent();
      session.addIntent(intent);

      await generateAndSendSummary(session, mockConfig);

      const filePath = mockWriteFile.mock.calls[0][0] as string;
      expect(filePath).toBe(`data/meetings/2026-03-27-${session.meetingId}.md`);
    });

    it('should create directory with recursive option', async () => {
      const intent = createIntent();
      session.addIntent(intent);

      await generateAndSendSummary(session, mockConfig);

      expect(mockMkdir).toHaveBeenCalledWith('data/meetings', { recursive: true });
    });
  });
});
