/**
 * End-of-meeting summary generator.
 * Issue #6 — NostraAIAgent.
 * Generates markdown summary, saves locally, sends via Telegram.
 */

import { writeFile, mkdir } from 'node:fs/promises';
import axios from 'axios';
import type { MeetingSession } from './session.js';
import type { OpenClawConfig } from './config.js';
import type { LlmClient } from './llm.js';

const TELEGRAM_MAX_LENGTH = 4096;

export async function generateAndSendSummary(
  session: MeetingSession,
  config: OpenClawConfig,
  llmClient?: LlmClient,
): Promise<void> {
  const markdown = buildMarkdown(session);

  await saveToFile(session, markdown);

  if (llmClient?.inferAndDeliver) {
    try {
      await llmClient.inferAndDeliver(
        'Please send this meeting summary to the user:\n\n' + markdown,
      );
      return;
    } catch (error) {
      console.error('Failed to deliver summary via inferAndDeliver, falling back to Telegram:', error);
    }
  }

  await sendToTelegram(markdown, config);
}

function buildMarkdown(session: MeetingSession): string {
  if (session.intents.length === 0) {
    return 'No action items detected in this meeting.';
  }

  const date = formatDate(session.startTime);
  const issuesSection = buildIssuesSection(session);
  const decisionsSection = buildDecisionsSection(session);
  const itemsSection = buildItemsSection(session);

  return `# Meeting Summary
**Date:** ${date}
**Meeting:** ${session.url}

## GitHub Issues Created
${issuesSection}

## Decisions
${decisionsSection}

## All Detected Items
${itemsSection}

---
*Generated by MeetingClaw*`;
}

function formatDate(date: Date): string {
  const year = date.getUTCFullYear();
  const month = String(date.getUTCMonth() + 1).padStart(2, '0');
  const day = String(date.getUTCDate()).padStart(2, '0');
  const hours = String(date.getUTCHours()).padStart(2, '0');
  const minutes = String(date.getUTCMinutes()).padStart(2, '0');
  return `${year}-${month}-${day} ${hours}:${minutes}`;
}

function buildIssuesSection(session: MeetingSession): string {
  if (session.createdIssues.length === 0) {
    return 'None';
  }

  return session.createdIssues
    .map((issue) => `- [${issue.title}](${issue.issueUrl})`)
    .join('\n');
}

function buildDecisionsSection(session: MeetingSession): string {
  if (session.decisions.length === 0) {
    return 'None';
  }

  return session.decisions.map((d) => `- ${d}`).join('\n');
}

function buildItemsSection(session: MeetingSession): string {
  return session.intents
    .map((intent) => {
      const ownerPart = intent.owner ? ` -> ${intent.owner}` : '';
      return `- **${intent.type}** [${intent.priority}]: ${intent.text}${ownerPart}`;
    })
    .join('\n');
}

async function saveToFile(session: MeetingSession, markdown: string): Promise<void> {
  const dir = 'data/meetings';
  const dateStr = session.startTime.toISOString().split('T')[0];
  const filePath = `${dir}/${dateStr}-${session.meetingId}.md`;

  try {
    await mkdir(dir, { recursive: true });
    await writeFile(filePath, markdown, 'utf-8');
  } catch (error) {
    console.error('Failed to save summary file:', error);
  }
}

async function sendToTelegram(markdown: string, config: OpenClawConfig): Promise<void> {
  if (!config.telegramBotToken || !config.telegramChatId) {
    return;
  }

  const url = `https://api.telegram.org/bot${config.telegramBotToken}/sendMessage`;
  const text = markdown.length > TELEGRAM_MAX_LENGTH
    ? markdown.slice(0, TELEGRAM_MAX_LENGTH)
    : markdown;

  try {
    await axios.post(url, {
      chat_id: config.telegramChatId,
      text,
      parse_mode: 'Markdown',
    });
  } catch (error) {
    console.error('Failed to send summary to Telegram:', error);
  }
}
